CREATE TABLE temp (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message    VARCHAR(255),
    status     VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGSERIAL,
    login_id VARCHAR(50) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(20) DEFAULT 'active' NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    
    -- 제약 조건 정의
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_login_id UNIQUE (login_id),
    CONSTRAINT uk_users_nickname UNIQUE (nickname),
    CONSTRAINT chk_users_status CHECK (status = 'active' OR status = 'suspended' OR status = 'deleted'),
    CONSTRAINT chk_users_login_id_len CHECK (LENGTH(login_id) >= 2),
    CONSTRAINT chk_users_nickname_len CHECK (LENGTH(nickname) >= 1)
);

-- 테이블 및 컬럼 주석(Comment) 추가
COMMENT ON TABLE users IS '사용자 마스터 테이블';
COMMENT ON COLUMN users.id IS '내부 식별자 (외부 노출 지양, FK 조인용)';
COMMENT ON COLUMN users.login_id IS '사용자가 로그인 시 입력하는 ID (변경 불가)';
COMMENT ON COLUMN users.nickname IS '화면에 표시되는 사용자 명 (변경 가능)';
COMMENT ON COLUMN users.password_hash IS 'BCrypt 해시값';
COMMENT ON COLUMN users.status IS '계정 상태 (active, suspended, deleted)';
COMMENT ON COLUMN users.last_login_at IS '최종 로그인 시각';
COMMENT ON COLUMN users.created_at IS '가입 시각';
COMMENT ON COLUMN users.updated_at IS '최종 수정 시각';

CREATE TABLE categories (
    id            BIGSERIAL   PRIMARY KEY,
    name          VARCHAR(50) NOT NULL,
    color         VARCHAR(7)  NOT NULL DEFAULT '#64748b',
    display_order INTEGER     NOT NULL DEFAULT 0,
    is_default    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE transactions (
    id               BIGSERIAL    PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    transaction_date DATE         NOT NULL,
    merchant         VARCHAR(200) NOT NULL,
    category_id      BIGINT,
    amount           BIGINT       NOT NULL,
    card_name        VARCHAR(50),
    installment      INTEGER      NOT NULL DEFAULT 1,
    status           VARCHAR(20)  NOT NULL DEFAULT '승인',
    memo             TEXT,
    tag              VARCHAR(100),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_transactions_user     FOREIGN KEY (user_id)     REFERENCES users(id)      ON DELETE CASCADE,
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT chk_transactions_amount      CHECK (amount >= 0),
    CONSTRAINT chk_transactions_installment CHECK (installment BETWEEN 1 AND 60),
    CONSTRAINT uk_transactions_dedup  UNIQUE (user_id, transaction_date, merchant, amount, card_name)
);
