CREATE TABLE monthly_goals (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id             BIGINT         NOT NULL,
    goal_month          DATE           NOT NULL,
    title               VARCHAR(100)   NOT NULL,
    target_category     VARCHAR(100)   NOT NULL,
    reduction_ratio     NUMERIC(5, 4)  NOT NULL,
    baseline_amount     BIGINT         NOT NULL,
    monthly_save        BIGINT         NOT NULL,
    status              VARCHAR(20)    NOT NULL DEFAULT 'active',
    actual_saved        BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_monthly_goals PRIMARY KEY (id),
    CONSTRAINT fk_monthly_goals_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_monthly_goals_user_month UNIQUE (user_id, goal_month),
    CONSTRAINT chk_monthly_goals_month_first_day
        CHECK (EXTRACT(DAY FROM goal_month) = 1),
    CONSTRAINT chk_monthly_goals_title
        CHECK (LENGTH(TRIM(title)) > 0),
    CONSTRAINT chk_monthly_goals_target_category
        CHECK (LENGTH(TRIM(target_category)) > 0),
    CONSTRAINT chk_monthly_goals_reduction_ratio
        CHECK (reduction_ratio > 0 AND reduction_ratio <= 1),
    CONSTRAINT chk_monthly_goals_baseline_amount
        CHECK (baseline_amount > 0),
    CONSTRAINT chk_monthly_goals_monthly_save
        CHECK (monthly_save > 0 AND monthly_save <= baseline_amount),
    CONSTRAINT chk_monthly_goals_status
        CHECK (status IN ('active', 'completed', 'stopped')),
    CONSTRAINT chk_monthly_goals_actual_saved
        CHECK (actual_saved IS NULL OR actual_saved >= 0)
);

COMMENT ON TABLE monthly_goals IS '사용자별 월 절감 목표';
COMMENT ON COLUMN monthly_goals.goal_month IS '목표 연월의 첫째 날';
COMMENT ON COLUMN monthly_goals.target_category IS '목표 생성 시점의 카테고리명 스냅샷';
COMMENT ON COLUMN monthly_goals.reduction_ratio IS '0 초과 1 이하의 절감 비율';
COMMENT ON COLUMN monthly_goals.baseline_amount IS '목표 설정 기준 금액';
COMMENT ON COLUMN monthly_goals.monthly_save IS '월 절감 목표 금액';
COMMENT ON COLUMN monthly_goals.actual_saved IS '완수 시 확정 절감액';
