spring:
  application:
    name: agilemvp
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level [%X{traceId}] --- [%-15.15thread] %-40.40logger{39} : %msg%n"
  level:
    root: INFO
    cop.kbds.agilemvp: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: ASC
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
