DROP TABLE IF EXISTS temp;
CREATE TABLE temp (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message    VARCHAR(255),
    status     VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    updated_at TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id      VARCHAR(50)  NOT NULL UNIQUE,
    nickname      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'active',
    last_login_at TIMESTAMP,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50)  NOT NULL UNIQUE,
    color         VARCHAR(7)   NOT NULL DEFAULT '#64748b',
    display_order INTEGER      NOT NULL DEFAULT 0,
    is_default    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE transactions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL,
    transaction_date DATE         NOT NULL,
    merchant         VARCHAR(200) NOT NULL,
    category_id      BIGINT,
    amount           BIGINT       NOT NULL,
    card_name        VARCHAR(50),
    installment      INTEGER      NOT NULL DEFAULT 1,
    status           VARCHAR(20)  NOT NULL DEFAULT '승인',
    memo             TEXT,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transactions_user     FOREIGN KEY (user_id)     REFERENCES users(id)      ON DELETE CASCADE,
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT uk_transactions_dedup    UNIQUE (user_id, transaction_date, merchant, amount, card_name)
);
